'Build the on-demand app menu from extension declarations.'
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
build = (root / 'build.sh').read_text()
names = re.search(r'for n in ([\w ]+); do', build).group(1).split()
rows = []
for name in names:
    s = (root / 'kexts' / (name + '.c')).read_text()
    if not re.search(r'kext_header\s*=\s*\{[^}]*KEXT_KIND_APP', s):
        continue
    desc = re.findall(r'const AppDesc \w+\s*=\s*\{(.*?)\};', s, re.S)
    assert len(desc) == 1, f'{name}: expected one AppDesc'
    title = re.search(r'\.title\s*=\s*("[^"]+")', desc[0])
    assert title, f'{name}: expected literal title'
    cat = re.search(r'\.category\s*=\s*(APP_CAT_\w+)', desc[0])
    cmds = re.findall(r'register_cmd\("([^"]+)"', s)
    exts = re.findall(r'register_opener\("([^"]*)"', s)
    rows.append('    {"sys/%s.kx", %s, "%s", "%s", %s},' %
                (name, title.group(1), ' '.join(cmds),
                 ' '.join(x or '*' for x in exts), cat.group(1) if cat else 'APP_CAT_AUTO'))
out = '/* App menu generated by tools/appcatalog.py. */\n' + '\n'.join(rows) + '\n'
(root / 'src' / 'appcatalog.inc').write_text(out)
print(f'App catalog: {len(rows)} apps available on demand')
